# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='desc',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
