# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='key',
            field=models.CharField(default='45SewoeqnNo', max_length=32),
            preserve_default=False,
        ),
    ]
